<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrenciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (DB::table('currencies')->count() > 0) {
            return;
        }
        
        $currencies = [
            ['id' => 1, 'code' => 'AFN', 'name' => 'Afghani', 'symbol' => '؋'],
            ['id' => 2, 'code' => 'ALL', 'name' => 'Lek', 'symbol' => 'Lek'],
            ['id' => 3, 'code' => 'ARS', 'name' => 'Argentine Peso', 'symbol' => '$'],
            ['id' => 4, 'code' => 'AUD', 'name' => 'Australian Dollar', 'symbol' => '$'],
            ['id' => 5, 'code' => 'AWG', 'name' => 'Aruban Guilder', 'symbol' => 'ƒ'],
            ['id' => 6, 'code' => 'AZN', 'name' => 'Azerbaijanian Manat', 'symbol' => 'ман'],
            ['id' => 7, 'code' => 'BAM', 'name' => 'Convertible Marks', 'symbol' => 'KM'],
            ['id' => 8, 'code' => 'BDT', 'name' => 'Bangladeshi Taka', 'symbol' => '৳'],
            ['id' => 9, 'code' => 'BBD', 'name' => 'Barbados Dollar', 'symbol' => '$'],
            ['id' => 10, 'code' => 'BGN', 'name' => 'Bulgarian Lev', 'symbol' => 'лв'],
            ['id' => 11, 'code' => 'BMD', 'name' => 'Bermudian Dollar', 'symbol' => '$'],
            ['id' => 12, 'code' => 'BND', 'name' => 'Brunei Dollar', 'symbol' => '$'],
            ['id' => 13, 'code' => 'BOB', 'name' => 'BOV Boliviano Mvdol', 'symbol' => '$b'],
            ['id' => 14, 'code' => 'BRL', 'name' => 'Brazilian Real', 'symbol' => 'R$'],
            ['id' => 15, 'code' => 'BSD', 'name' => 'Bahamian Dollar', 'symbol' => '$'],
            ['id' => 16, 'code' => 'BWP', 'name' => 'Pula', 'symbol' => 'P'],
            ['id' => 17, 'code' => 'BYR', 'name' => 'Belarussian Ruble', 'symbol' => '₽'],
            ['id' => 18, 'code' => 'BZD', 'name' => 'Belize Dollar', 'symbol' => 'BZ$'],
            ['id' => 19, 'code' => 'CAD', 'name' => 'Canadian Dollar', 'symbol' => '$'],
            ['id' => 20, 'code' => 'CHF', 'name' => 'Swiss Franc', 'symbol' => 'CHF'],
            ['id' => 21, 'code' => 'CLP', 'name' => 'CLF Chilean Peso Unidades de fomento', 'symbol' => '$'],
            ['id' => 22, 'code' => 'CNY', 'name' => 'Yuan Renminbi', 'symbol' => '¥'],
            ['id' => 23, 'code' => 'COP', 'name' => 'COU Colombian Peso Unidad de Valor Real', 'symbol' => '$'],
            ['id' => 24, 'code' => 'CRC', 'name' => 'Costa Rican Colon', 'symbol' => '₡'],
            ['id' => 25, 'code' => 'CUP', 'name' => 'CUC Cuban Peso Peso Convertible', 'symbol' => '₱'],
            ['id' => 26, 'code' => 'CZK', 'name' => 'Czech Koruna', 'symbol' => 'Kč'],
            ['id' => 27, 'code' => 'DKK', 'name' => 'Danish Krone', 'symbol' => 'kr'],
            ['id' => 28, 'code' => 'DOP', 'name' => 'Dominican Peso', 'symbol' => 'RD$'],
            ['id' => 29, 'code' => 'EGP', 'name' => 'Egyptian Pound', 'symbol' => '£'],
            ['id' => 30, 'code' => 'EUR', 'name' => 'Euro', 'symbol' => '€'],
            ['id' => 31, 'code' => 'FJD', 'name' => 'Fiji Dollar', 'symbol' => '$'],
            ['id' => 32, 'code' => 'FKP', 'name' => 'Falkland Islands Pound', 'symbol' => '£'],
            ['id' => 33, 'code' => 'GBP', 'name' => 'Pound Sterling', 'symbol' => '£'],
            ['id' => 34, 'code' => 'GIP', 'name' => 'Gibraltar Pound', 'symbol' => '£'],
            ['id' => 35, 'code' => 'GTQ', 'name' => 'Quetzal', 'symbol' => 'Q'],
            ['id' => 36, 'code' => 'GYD', 'name' => 'Guyana Dollar', 'symbol' => '$'],
            ['id' => 37, 'code' => 'HKD', 'name' => 'Hong Kong Dollar', 'symbol' => '$'],
            ['id' => 38, 'code' => 'HNL', 'name' => 'Lempira', 'symbol' => 'L'],
            ['id' => 39, 'code' => 'HRK', 'name' => 'Croatian Kuna', 'symbol' => 'kn'],
            ['id' => 40, 'code' => 'HUF', 'name' => 'Forint', 'symbol' => 'Ft'],
            ['id' => 41, 'code' => 'IDR', 'name' => 'Rupiah', 'symbol' => 'Rp'],
            ['id' => 42, 'code' => 'ILS', 'name' => 'New Israeli Sheqel', 'symbol' => '₪'],
            ['id' => 43, 'code' => 'IRR', 'name' => 'Iranian Rial', 'symbol' => '﷼'],
            ['id' => 44, 'code' => 'ISK', 'name' => 'Iceland Krona', 'symbol' => 'kr'],
            ['id' => 45, 'code' => 'JMD', 'name' => 'Jamaican Dollar', 'symbol' => 'J$'],
            ['id' => 46, 'code' => 'JPY', 'name' => 'Yen', 'symbol' => '¥'],
            ['id' => 47, 'code' => 'KGS', 'name' => 'Som', 'symbol' => 'лв'],
            ['id' => 48, 'code' => 'KHR', 'name' => 'Riel', 'symbol' => '៛'],
            ['id' => 49, 'code' => 'KPW', 'name' => 'North Korean Won', 'symbol' => '₩'],
            ['id' => 50, 'code' => 'KRW', 'name' => 'Won', 'symbol' => '₩'],
            ['id' => 51, 'code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'symbol' => '$'],
            ['id' => 52, 'code' => 'KZT', 'name' => 'Tenge', 'symbol' => 'лв'],
            ['id' => 53, 'code' => 'LAK', 'name' => 'Kip', 'symbol' => '₭'],
            ['id' => 54, 'code' => 'LBP', 'name' => 'Lebanese Pound', 'symbol' => '£'],
            ['id' => 55, 'code' => 'LKR', 'name' => 'Sri Lanka Rupee', 'symbol' => '₨'],
            ['id' => 56, 'code' => 'LRD', 'name' => 'Liberian Dollar', 'symbol' => '$'],
            ['id' => 57, 'code' => 'LTL', 'name' => 'Lithuanian Litas', 'symbol' => 'Lt'],
            ['id' => 58, 'code' => 'LVL', 'name' => 'Latvian Lats', 'symbol' => 'Ls'],
            ['id' => 59, 'code' => 'MKD', 'name' => 'Denar', 'symbol' => 'ден'],
            ['id' => 60, 'code' => 'MNT', 'name' => 'Tugrik', 'symbol' => '₮'],
            ['id' => 61, 'code' => 'MUR', 'name' => 'Mauritius Rupee', 'symbol' => '₨'],
            ['id' => 62, 'code' => 'MXN', 'name' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI]', 'symbol' => '$'],
            ['id' => 63, 'code' => 'MYR', 'name' => 'Malaysian Ringgit', 'symbol' => 'RM'],
            ['id' => 64, 'code' => 'MZN', 'name' => 'Metical', 'symbol' => 'MT'],
            ['id' => 65, 'code' => 'NGN', 'name' => 'Naira', 'symbol' => '₦'],
            ['id' => 66, 'code' => 'NIO', 'name' => 'Cordoba Oro', 'symbol' => 'C$'],
            ['id' => 67, 'code' => 'NOK', 'name' => 'Norwegian Krone', 'symbol' => 'kr'],
            ['id' => 68, 'code' => 'NPR', 'name' => 'Nepalese Rupee', 'symbol' => '₨'],
            ['id' => 69, 'code' => 'NZD', 'name' => 'New Zealand Dollar', 'symbol' => '$'],
            ['id' => 70, 'code' => 'OMR', 'name' => 'Rial Omani', 'symbol' => '﷼'],
            ['id' => 71, 'code' => 'PAB', 'name' => 'USD Balboa US Dollar', 'symbol' => 'B/.'],
            ['id' => 72, 'code' => 'PEN', 'name' => 'Nuevo Sol', 'symbol' => 'S/.'],
            ['id' => 73, 'code' => 'PHP', 'name' => 'Philippine Peso', 'symbol' => 'Php'],
            ['id' => 74, 'code' => 'PKR', 'name' => 'Pakistan Rupee', 'symbol' => '₨'],
            ['id' => 75, 'code' => 'PLN', 'name' => 'Zloty', 'symbol' => 'zł'],
            ['id' => 76, 'code' => 'PYG', 'name' => 'Guarani', 'symbol' => 'Gs'],
            ['id' => 77, 'code' => 'QAR', 'name' => 'Qatari Rial', 'symbol' => '﷼'],
            ['id' => 78, 'code' => 'RON', 'name' => 'New Leu', 'symbol' => 'lei'],
            ['id' => 79, 'code' => 'RSD', 'name' => 'Serbian Dinar', 'symbol' => 'Дин.'],
            ['id' => 80, 'code' => 'RUB', 'name' => 'Russian Ruble', 'symbol' => 'руб'],
            ['id' => 81, 'code' => 'SAR', 'name' => 'Saudi Riyal', 'symbol' => '﷼'],
            ['id' => 82, 'code' => 'SBD', 'name' => 'Solomon Islands Dollar', 'symbol' => '$'],
            ['id' => 83, 'code' => 'SCR', 'name' => 'Seychelles Rupee', 'symbol' => '₨'],
            ['id' => 84, 'code' => 'SEK', 'name' => 'Swedish Krona', 'symbol' => 'kr'],
            ['id' => 85, 'code' => 'SGD', 'name' => 'Singapore Dollar', 'symbol' => '$'],
            ['id' => 86, 'code' => 'SHP', 'name' => 'Saint Helena Pound', 'symbol' => '£'],
            ['id' => 87, 'code' => 'SOS', 'name' => 'Somali Shilling', 'symbol' => 'S'],
            ['id' => 88, 'code' => 'SRD', 'name' => 'Surinam Dollar', 'symbol' => '$'],
            ['id' => 89, 'code' => 'SVC', 'name' => 'USD El Salvador Colon US Dollar', 'symbol' => '$'],
            ['id' => 90, 'code' => 'SYP', 'name' => 'Syrian Pound', 'symbol' => '£'],
            ['id' => 91, 'code' => 'THB', 'name' => 'Baht', 'symbol' => '฿'],
            ['id' => 92, 'code' => 'TRY', 'name' => 'Turkish Lira', 'symbol' => 'TL'],
            ['id' => 93, 'code' => 'TTD', 'name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$'],
            ['id' => 94, 'code' => 'TWD', 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$'],
            ['id' => 95, 'code' => 'UAH', 'name' => 'Hryvnia', 'symbol' => '₴'],
            ['id' => 96, 'code' => 'USD', 'name' => 'US Dollar', 'symbol' => '$'],
            ['id' => 97, 'code' => 'UYU', 'name' => 'UYI Uruguay Peso en Unidades Indexadas', 'symbol' => '$U'],
            ['id' => 98, 'code' => 'UZS', 'name' => 'Uzbekistan Sum', 'symbol' => 'лв'],
            ['id' => 99, 'code' => 'VEF', 'name' => 'Bolivar Fuerte', 'symbol' => 'Bs'],
            ['id' => 100, 'code' => 'VND', 'name' => 'Dong', 'symbol' => '₫'],
            ['id' => 101, 'code' => 'XCD', 'name' => 'East Caribbean Dollar', 'symbol' => '$'],
            ['id' => 102, 'code' => 'YER', 'name' => 'Yemeni Rial', 'symbol' => '﷼'],
            ['id' => 103, 'code' => 'ZAR', 'name' => 'Rand', 'symbol' => 'R'],
        ];

        DB::table('currencies')->insert($currencies);
    }
}
